import { type Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
};


export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <div className="flex h-screen w-screen items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white">
      {/*  Menu */}
      <div className="fixed top-8 left-0 z-10 flex h-[400px] w-72 flex-col justify-between overflow-y-auto rounded-r-[30px] border border-solid border-[#f2f2f2] bg-[#f6f6f6] shadow-[0_12px_24px_0_#B0B0B068] scrollbar-hide">
        <div className="flex flex-col gap-4 p-6">
          <Link href='/invoices' className="text-xl font-semibold text-neutral-800">Invoices</Link>
          <div className="flex flex-col gap-2">
            <Link href="/invoices/list">
              <p className="text-sm font-semibold text-neutral-800">List</p>
            </Link>
            <Link href="/invoices/create">
              <p className="text-sm font-semibold text-neutral-800">Create</p>
            </Link>
          </div>
        </div>
      </div>
      {children}
    </div>
  );
}
